### ISSUE TITLE
Transdroid displays erroneous ratios and upload with qBittorrent 3.2 server [2.5.0 beta 1]

### ISSUE THREAD

**Issue by wopian** [erickok/transdroid#212]
Don't know if this was in the last stable version as it didn't work with qBittorrent 3.2 at the time.

Values reported by qBittorent 3.2:
Download: 27.3 MiB
Upload: 104.2 MiB
Ratio: 3.57

Values reported by Transdroid 2.5.0 b1:
Download: 27.4 MB
Upload: 8608.2 GB
Ratio: 321754.0 (*if only it were true*)

Old examples of same torrent:

![](https://i.imgur.com/mSHSEgT.png)
![](https://i.imgur.com/k6EEJKA.png)

**Comment by erickok** [comment]
Thanks for the report. I fixed this. One note (for my future self, if nobody else): the downloaded and uploaded amounts are not directly given by the qBittorrent API. Instead, they are calculated from the total size together with the progress or ratio respectively.
```java
(long) (size * progress)
(long) (size * ratio)
```
This causes (slight) imperfections, since the base progress and ratio values are rounded.

**Comment by wopian** [comment]
:+1:
