### ISSUE TITLE
Speed limits not working and label issues - qBittorrent

### ISSUE THREAD

**Issue by SetsunaF** [erickok/transdroid#213]
-Speed limits are not working on the latest Transdroid with qBittorrent, when I try to set the speed or reset I receive a message "Internal error building request", and sometimes the speed dialog does not appear and I have to close (with back button) and reopen Transdroid.

-Also when a download is finished the "Uploaded" label (below the torrent name) reports the wrong value, I think it's reporting the uploaded size in kilobytes but there is a label with "GB" next to it.

Transdroid 2.5.0 beta 1
qBittorrent v3.2.0
Android 4.1.2

**Comment by erickok** [comment]
qBittorrent's web UI does not permit setting the speeds limits via their web interface API. I tried to mimic a call like the settings dialog does, but this does not seem to work. We'll have to wait until qBittorrent adds a proper settings method.

Note that the uploaded value (and ratio) values were incorrect in 2.5.0 beta 1, but this issue has since been solved. See #212.
