### ISSUE TITLE
Self-signed cert trusting unsafe

### ISSUE THREAD

**Issue by bjoli** [erickok/transdroid#292]
Hi there!

I am a huge fan, and using transdroid is easy and works well. However, I recently decided to make my Pi accesible from the internet. I set up stunnel with a self-generated cert, and I was a bit put back. The way to secure transdroid with self-signed certs is tedious, and requires manually entering a SHA-1 fingerprint.

I am a firm believer in sane defaults, and this is not what I would call sane. What most people want when using a self-signed certificate is TOFU (trust on first use). Maybe the default behaviour could be to accept the certificate, and warn on changes (with a checkbox to ignore all errors or to not do any verifications). I would have loved to have a PR ready for you, but I am no programmer. 

Best regards
Linus

**Comment by kecksk0enig** [comment]
Hi!
I recently also used self signed certs, and entering the sha-1 was a pain in the ass.
however I think since letsencrypt.org allowes one to create unlimited amount of VALID DV Certs , one should use one of those instead of a selfsigned one.

Another way is to import your OWN CA into your andorids truststore as a trusted CA.

**Comment by bjoli** [comment]
I see what you mean, but I don't agree. We will have self-signed certs for a long time yet, and the jump from "only trust valid certs" to "trust all, regardless" is too big. There are still uses for self signed certs , like for servers where you don't have root access and still want to be able to run a torrent daemon :)

And then let's not get started on the mess that is free dynamic dns. They could just mitm you with a wildcard cert ("*.mo-ip.com" ), so unless you manually type in the sha-1 you are still vulnerable :)

(well, that is probably a bit over the top. I don't think anyone wants to mitm my torrent traffic. It would be different if this would have been owncloud or something)

**Comment by erickok** [comment]
`the jump from "only trust valid certs" to "trust all, regardless" is too big`
I agree, and that's why the option is there to enter your own SHA-1.
`What most people want when using a self-signed certificate is TOFU (trust on first use). `
I understand this option but I actually don't find that secure at all. Unless you manually verify this (which, admit it, nobody does) it is still no real secure option.

So my solution is: Either go through the one time pain of entering the SHA-1 hash or get a valid CA certificate, such as the free certificates of StartSSL. I hope you can see my reasoning.
