### ISSUE TITLE
Transdroid  search engine missing from ttorrent 

### ISSUE THREAD

**Issue by everskyle** [erickok/transdroid#294]
I don't know what else to say really.  I've never experienced any problems before now and before marshmallow 6.0.1. My phone freezes then ttorrent and transdroid main becomes corrupt along with a lot of other apps forcing me to delete and reinstall.  This time the ttorrent pro app is gone,  poof, not in the app store anymore and transdroid is missing from ttorrent light.

**Comment by erickok** [comment]
I am not sure I understand your issue.

Transdroid is an app that is not in the Play Store. You can get it from here. Transdrone is the little brother app without search, etc. and IS available in the Play Store. tTorrent is a different app (which I do not develop) and is in the Play Store. Both Transdroid and tTorrent make use of a shared search module (called Torrent Search), which is not directly available from the Play Store but your app (either Transdroid or tTorrent) should propose to you to download.

**Comment by everskyle** [comment]
Sorry I have the new galaxy s7 edge and was having problems with transdroid through ttorrent pro.  I thought maybe it was an issue with the phone but I see that the play store had transdroid search engine removed from ttorrent for violating their malicious app policy.  Is there anyway to keep using transdroid search engine through another app?  If you could point me in the right direction It would be greatly appreciated. Thank you for your time. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by erickok** [comment]
I'm still not sure what the problem is.

To use Transdroid, grab it from the website at www.transdroid.org/download and install it. When you start a search it will ask you to instal the Torrent Search module, which it will link to or you can manually download it from the same website.

To use tTorrent you can grab it from the Play Store. When starting a search it will ask you do download and install the Torrent Search module, or you can grab it manually from www.transdroid.org/download

**Comment by erickok** [comment]
I understand now that tTorrent had to remove the search fro their app or be removed from the Play Store. This is their unfortunate issue though, nothing to do with Transdroid. I fully support their app and we both have a strong relationship.
