### ISSUE TITLE
Crash when loading main page

### ISSUE THREAD

**Issue by moose392** [erickok/transdroid#315]
As soon as I set up my Dediseedbox and return to the main page, it starts loading then crashes.
This isnt the full logcat, more of a filtered version since Im not sure if there is any personal info in there.

[logcat_filtered.txt](https://github.com/erickok/transdroid/files/305262/logcat_filtered.txt)

Edit: I forgot to add that restarting the app also results in an instantaneous crash.

**Comment by TulioLazarini** [comment]
Hello, same issue here. I don't know how to collect logs to send, but I can't load Transdroid (Transdrone) anymore on my new phone. On my old Moto G2, everything worked fine (using Android 6.0), but now on my Moto X 2nd Gen, More information about the phone:
- Android version: 6.0.1
- Security patch level: March 1st 2016
- Kernel version: 3.10.49-gf0dab7f, Feb 19 2016
- System version: 24.61.52.lux_retla_ds.retla.en.01 retbr

**Comment by TulioLazarini** [comment]
Oh, btw, I backtested older versions, till former 2.3.0, and all of them crashed. Oh, by the way, I forgot to specify what kind of server I'm trying to configure. I use a shared seedbox, running rtorrent 0.9.2/0.13.2, that requires authentication, and uses a specific RPC folder (eg: \box1\plugins\httprpc\action.php). Thanks in advance.

**Comment by moose392** [comment]
Good to know I'm not the only one. You are using the stock, unmodified ROM, right? No root or custom recovery either?
Odds are, my logs provide sufficient information to find a solution.
However, this is the command I used on Windows: adb logcat -d > logcat.txt
I used Notepad++ to filter out all lines that didn't seem relevant.

**Comment by TulioLazarini** [comment]
Hello,

Yes, I'm using the stock firmware ROM provided by Motorola, unrooted and
unmodified in any way. What Android version are you using?
Em 9 de jun de 2016 3:37 PM, "moose392" <notifications@github.com> escreveu:

Good to know I'm not the only one. You are using the stock, unmodified ROM,
right? No root or custom recovery either?
Odds are, my logs provide sufficient information to find a solution.
However, this is the command I used on Windows: adb logcat -d > logcat.txt
I used Notepad++ to filter out all lines that didn't seem relevant.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/erickok/transdroid/issues/315#issuecomment-224987100>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMGFVKGQ8ydlxS3W-LyYOSTxDz7GDwq7ks5qKF1egaJpZM4IxKfv>
.

**Comment by moose392** [comment]
I am using the following:
OnePlus 2
Exodus (Android 6.0.1), a custom ROM

I hoped the custom ROM was not the issue since this app has worked on it in the past. Assuming you are having the same issue, then that is confirmed.
Maybe if you can get a log, we can run a diff on it and see how they compare.

**Comment by TulioLazarini** [comment]
Glad to help! However, I don't have Android Studio installed, nor have adb.
How can I get application logs to send?

I am using the following:
OnePlus 2
Exodus (Android 6.0.1), a custom ROM

I hoped the custom ROM was not the issue since this app has worked on it in
the past. Assuming you are having the same issue, then that is confirmed.
Maybe if you can get a log, we can run a diff on it and see how they
compare.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/erickok/transdroid/issues/315#issuecomment-224990592>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMGFVM6LWeOBIg4WrK0f07zhGCDe4C8Oks5qKGBWgaJpZM4IxKfv>
.

**Comment by moose392** [comment]
I think maybe you can use a logcat app?

**Comment by erickok** [comment]
Odd, it is a crash in the rTorrent connection part, which is extensively used and I haven't received similar reports yet. It is probably in incompatibility with your rTorrent version and/or your server configuration. Transdroid gets an unexpected result and cannot parse the response, possibly because it simply gets served an error page instead of the proper xml. 

Regardless, Transdroid should now crash. Could you please uninstall the app, reinstall and enter your settings again, making sure that your password and everything is correct?

**Comment by TulioLazarini** [comment]
Eric,

Thanks for your attention. I personally don't believe it's a compatibility
issue with my rTorrent version, because this very phone used to connect
perfectly well until Android gets updated to 6.0.1. I tried to uninstall,
reinstall and reconfigure, and no luck at all.

I have absolute sure that all parameters are fine, copied settings.json
from my Android tablet (which is working ok) and imported it on Moto X
Play, and immediately after configuration, it tries to connect and then
crashes.

Tried to use logcat apps to view what's going on, but no luck, no messages
about the crash on logcat. If I can do some local teste to help you find
the solution, I'm happy to be at your service.
Em 10 de jun de 2016 4:17 AM, "Eric Kok" <notifications@github.com>
escreveu:

**Comment by moose392** [comment]
I am also 100% certain that the settings are all entered correctly. I have wiped data and reinstalled many times, all with the same result.

**Comment by moose392** [comment]
According to the Dediseedbox site, their SCGI folder is at /rutorrent/plugins/httprpc/action.php
If I log in to the web interface on my computer and paste that in, it seems as if it just loads a text file, which reads "false." Please refer to the attached image. Is this the expected behavior?

![scgi](https://cloud.githubusercontent.com/assets/6157620/15982257/4199edee-2f40-11e6-8f94-3290fd4e878c.PNG)

**Comment by erickok** [comment]
Sorry if I have the impression that the blame is with you, it's not, it's the app that is somehow misbehaving. I'm trying to isolate the situation under which it exists, add I can't reproduce it.

That SCGI mount point is correct, they use the tTorrent SCGI plugin rather than having the webserver manage it. Regardless it's not an URL you can just visit.

**Comment by moose392** [comment]
If there is any way I can help, let me know. 
@TulioLazarini Ill guide you through a log capture if you would like. Maybe there is something additional/different in yours that could be of help.

**Comment by TulioLazarini** [comment]
Hey @moose392, I'd appreciate your help. Tried some logcat apps, but no
luck with any of them. Btw, the same happened when I tried to visit
HTTPCRPC URL from my seedbox, the response page says 'false'.
Em 11 de jun de 2016 1:28 PM, "moose392" <notifications@github.com>
escreveu:

**Comment by moose392** [comment]
@TulioLazarini you can email me at throwaway@eurofreak.org
I made another email in case bots find and sell it to spammers.

**Comment by TulioLazarini** [comment]
Hello @erickok, with help acquired from @moose392, I got adb logcat running on my Windows machine, with my Android 6.0.1 phone on USB debug mode. I got several occurrences just like that, generated the very moment app tries to connect to rTorrent host:

`06-21 21:42:02.699 20237 20252 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
06-21 21:42:02.699 20237 20252 E AndroidRuntime: Process: org.transdroid.lite, PID: 20237
06-21 21:42:02.699 20237 20252 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.auth.DigestScheme.isGbaScheme(DigestScheme.java:210)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.auth.DigestScheme.processChallenge(DigestScheme.java:176)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.DefaultRequestDirector.processChallenges(DefaultRequestDirector.java:1125)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:1008)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:518)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:580)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:503)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:481)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:379)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:196)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.daemon.Rtorrent.RtorrentAdapter.makeRtorrentCall(RtorrentAdapter.java:338)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.daemon.Rtorrent.RtorrentAdapter.executeTask(RtorrentAdapter.java:113)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:79)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:938)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.core.gui.TorrentsActivity_.access$2301(TorrentsActivity_.java:55)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.transdroid.core.gui.TorrentsActivity_$27.execute(TorrentsActivity_.java:682)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: f	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-21 21:42:02.699 20237 20252 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
06-21 21:42:02.702  1988  5017 W ActivityManager:   Force finishing activity org.transdroid.lite/org.transdroid.core.gui.TorrentsActivity_`

Hope it helps to find a solution. Thank you again.

**Comment by moose392** [comment]
@TulioLazarini It looks like you are using the lite version. I did not know one even existed.
@erickok I dont imagine the lite/full difference has any bearing on our issue.

**Comment by simoro** [comment]
Hello, same problem here, Oneplus 2 stock rom 6.0.1 all the settings are correct but the app crash at startup. 
rutorrent server with scgi script

**Comment by moose392** [comment]
@simoro was it working for you back on OOS 2.2.1? It was for me. I believe OnePlus changed something in the firmware.

**Comment by simoro** [comment]
@moose392 i never tested it before upgrading. But on other devices it works good. But none of them has 6.0.1 so i am not sure if it is an android issue or a phone issue..

**Comment by moose392** [comment]
Let's give @erickok some time to look into it and hope he implements a fix. I don't think there is anything more we can do at this point.

**Comment by TulioLazarini** [comment]
No solution so far. Transdroid still crashing on Android 6.0.1.

**Comment by dvhub** [comment]
Same issue on OnePlus 3 running stock rom (OxygenOS 3.2.2) and Transdrone 2.5.7.

**Comment by erickok** [comment]
Note to self: Certainly the issue is with Digest auth support under Android 6 (and later?). POssibly only on the OnePlus devices and/or custom ROMs.

**Comment by Woutifier** [comment]
I have this problem as well. Nexus 5x, Android 7 (stock)

**Comment by TTherouanne** [comment]
Hi, same issue with my Moto X Play (Android 6.0.1 stock)

**Comment by TulioLazarini** [comment]
Hey @TTherouanne, glad to see it isn't just me having issues with Android 6.0.1 stock here. @Woutifier has issues with Android 7. 
Dear @erickok, after some research on web, I found [this link](http://stackoverflow.com/questions/36262232/android-6-0-httpclient-issue-with-lg-g3-phone), with some useful information on how Android 6.0.1 onwards changed the implementation of DefaultHttpClient. In a flash, it recommends:
- Add a dependency compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1' to build.gradle.
- Replace DefaultHttpClient() to HttpClientBuilder.create().build()
And it should work. I don't know if this implementation is backward compatilble wit Android 2.x - 6.0, but should worth a try.

**Comment by erickok** [comment]
While I haven't looked into great details what causes the issue, the problem seems some Digest auth format that I do not yet support. Of course, first of all, the app should not crash. But after that I am not sure upgrading the Apache HttpClient to an external dependency is going to solve this. It might, it might now, I do not know. I have to find some time to work on it but it probably will not be before somewhere near the end of the month due to a very, very busy schedule. Sorry for the inconvenience I really hope to solve it soon.

**Comment by activoice** [comment]
On my Nexus 7 2013 tablet Transdroid works correctly. That tablet is running Android version 6.0.1 with android security patch level August 5, 2016

On my ZTE AXON 7 phone transdroid crashes right away when logging into DediSeedbox. This device is also running Android version 6.01 but this has security patch level Sept 1, 2016.

I'm wondering if there is something in that security patch that is causing the App to fail. I guess we'll know for sure if / when the tablet gets that security patch.

Neither device is rooted.

**Comment by moose392** [comment]
It worked fine on my Nexus 4 on 6.0.1 and now also on 7.0. For some reason, the bug is not 100% reproducible on android versions >= 6.0.1 so it is difficult to determine what exactly is the cause.
Hopefully Eric can pin it down using our logs.
I'm going to change ROMs on my OnePlus 2 soon (up to 7.X AOSP), and Ill report back if that fixes it, though I doubt it will.

**Comment by moose392** [comment]
It works now that I upgraded my OnePlus 2 to Android 7.0! I've had to do without this app for months, so this makes me so happy.

**Comment by Woutifier** [comment]
On my Nexus 5X it is now also working (Android 7.0), but it wasn't before, strange.

**Comment by khat17** [comment]
Hi all. I believe I sent in my logs and such via email already. This also happens on the Honor 5X. Did not have the issue when on Android 5.x but once I upgraded to 6.x this issue happened. The problem is with Android OS 6.x on some devices. Not sure why. I'm actually thinking of downgrading back to 5.x because I really love the app. Transdrone also has the same issue.

**Comment by TulioLazarini** [comment]
Hi,
I upgrade Transdroid version to 2.5.8 yesterday and tried to run this new version, but It still crashes.

**Comment by khat17** [comment]
@TulioLazarini - Going to try on Honor 5X and see if it still has same issue.

**Comment by khat17** [comment]
Same problem with new version on Honor 5X.

**Comment by erickok** [comment]
As this was/is an issue only on very specific phones running an old (unpatched yet modified) Android 6.0.1 version and only with Digest authentication (and I cannot reproduce it myself) I decided to not fix it. The danger of breaking other stuff by upgrading the Apache Http Client is not worth it for me at this stage. Sorry for anyone still impacted...
