### ISSUE TITLE
Rtorrent not working set priorities for individual files

### ISSUE THREAD

**Issue by prog-it** [erickok/transdroid#358]
In rtorrent, not working set the priority settings for individual files. For example, if you set the "Do not download" priority, the file continues to be downloading. If you look at the status of uploading a file via webui RUtorrent, the status showing as "NO download", although the file continues to be downloading. If you set the statuses for individual files via webui RUtorrent works successfully.

Tested on the latest versions of applications: Transdroid compiled from the github master branch, rtorrent (0.9.6) and libtorrent were compiled from the github master branch. 2017.03.16

Please, fix this bug.

**Comment by erickok** [comment]
There are some remarks to be made here. First, rTorrent actually only supports 3 priorities for files: Don't Download, Normal and High. So Transdroid's Low setting won't do anything (it will use Normal).

<img width="323" alt="screen shot 2017-11-14 at 20 46 13" src="https://user-images.githubusercontent.com/196453/32802263-c2946584-c97f-11e7-865f-7dca4b35f28c.png">

Having said that, I just tested with rTorrent 0.9.4/0.13.4 (and ruTorrent as UI to check) and it updates the priorities just fine. But I DO see the same issue you are having: the download continues despite being marked Don't Download. The full download eventually finished.

<img width="256" alt="screen shot 2017-11-14 at 20 55 
57" src="https://user-images.githubusercontent.com/196453/32802239-b32792ba-c97f-11e7-83f6-5bfba7728846.png">

I will have to close this as from the Transdroid point all seems to work fine. I would report a bug at the rTorrent project (and refer to this issue here).
