### ISSUE TITLE
Deluge Direct Connection (Non Web) Support

### ISSUE THREAD

**Issue by alonalbert** [erickok/transdroid#404]
Transdroid supports Deluge via it's web API rather than using the direct API. Is there a reason for this?

Using the Web API is problematic when using deluged & deluge-web services because it requires deleuge-web to be connected to the daemon before it can be used and every time the daemon restarts for whatever reason, the connection need to be reestablished.

Which means, i constantly have to open the web interface and connect before I can use the app.

**Comment by erickok** [comment]
The reason is because it's the dedicated (designed) way to connect to it over the web.

I think you should simply have it always connect to the same background daemon automatically. You can set this up in Deluge settings. Then you never have to manually connect anything again.

**Comment by alonalbert** [comment]
I don't think that's an accurate representation of the Deluge architecture.

Deluge is by design a client-server application. The native GUI's are clients that connect to a server via an RPC API over a secure socket. Even when running in standalone mode. 

The Web API is designed specifically to make it easy for a web application to use. It's JSON over HTTP architecture makes it ideal for Web apps but a native app shouldn't feel compelled to use it instead of the native RPC API.

I'm in the process of writing a Deluge RPC Adapter for Transdroid. It's mostly done, I still have a few DaemonTask's left to implement but the basic functionality is already working.

I'll send you a pull request when I'm done and you can reconsider :)

**Comment by erickok** [comment]
Sue happy to receive contributions. I just wonder what will happen because Transdroid is build with the idea of singular commands that you can fire off, not with a constant connected socket to some remote server. Since there is no service running or anything (and I think the details activity, for example, will even instantiate a new daemon), who manages the connection?

**Comment by alonalbert** [comment]
Yeah, I know Transdroid doesn't maintain an open connection. My Adapter is compliant with that. It opens a new connection and logs in for each request.

Also, when I submit my pull request, do you want ti squashed or do you squash when you merge it?

**Comment by alonalbert** [comment]
One more thing:
My new Adapter has a lot in common with the existing Adapter. Specifically, most String constants and a few utility methods.

I think it's a good idea to extract these into a common class.

Doing this would involve some changes to the existing Adapter of course.

Do you prefer extracting the shared items in the original pull request or should I send another pull request afterwards?

**Comment by erickok** [comment]
In one PR is fine. And we can squash the PR when merging, not problem. Thanks for your work!

For you interest, I am slowly starting to work on upgrading the adapters to move away from the Apache HTTP client and will restructure the way adapter are written a bit. (See for a preview the rewrite-connect branch.) Still very early though and your code wouldn't be as strongly affected since it won't be using any http based layer anyway.

**Comment by alonalbert** [comment]
Sent PR #407
