### ISSUE TITLE
2.5.12 crashing on backgrounding/closing

### ISSUE THREAD

**Issue by robross0606** [erickok/transdroid#462]
Every time I leave the app, it eventually crashes and I'm notified by the OS. This only started happening with the latest release. Going back to previous version.

**Comment by erickok** [comment]
Yes seems to be bugged on newer Android versions with the background
service enabled. You can disable this as a workaround.

**Comment by bicklp** [comment]
yes same for me on .12  going back to .11 for now
this is from my s9 dump

--------- beginning of crash
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: FATAL EXCEPTION: main
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: Process: org.transdroid.full, PID: 14167
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.transdroid.core.service.AlarmReceiver_: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.full/org.transdroid.core.service.AppUpdateService_ }: app is in background uid UidRecord{c5c7f0a u0a555 RCVR bg:+3m23s160ms idle procs:1 seq(0,0,0)}
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3397)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.full/org.transdroid.core.service.AppUpdateService_ }: app is in background uid UidRecord{c5c7f0a u0a555 RCVR bg:+3m23s160ms idle procs:1 seq(0,0,0)}
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1484)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:663)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:663)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at org.transdroid.core.service.AlarmReceiver.onReceive(AlarmReceiver.java:42)
10-11 09:58:30.784 10555 14167 14167 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)

**Comment by esion-net** [comment]
Same here. Android 8.0, Sony Xperia Compact.

**Comment by serdima** [comment]
Same here, crashing. RSS notifications are no longer working as of 2.5.12

**Comment by Ga22be** [comment]
Same here, Nexus 6P on Oreo

**Comment by pyrrhichios** [comment]
Same here, Galaxy S8 on Oreo.

**Comment by dcabro** [comment]
Same here, Xiaomi Mi 5, Android 8.0.0

**Comment by erickok** [comment]
I know; I'll fixed it as soon as I find some time. Sorry for the slowness, I will get to it soon.
