### ISSUE TITLE
[Question] How Does Adding Torrentd Work?

### ISSUE THREAD

**Issue by grravity** [erickok/transdroid#532]
Didn't see a doc on this anywhere, but how exactly does adding a torrent file you download to your phone and add to Transdroid work?
Does it download to the default folder on the bitorrent host? Is there anyway to specify certain folders to download to per file added?

**Comment by erickok** [comment]
If you download a torrent on your phone, either via a browser or otherwise, you can click it (for example the notification showiung that the .torrent file download finished, or in the Downloads app) and Transdroid should open. Transdroid will then send it to your server to add the torrent to your torrent client.

The torrent client will download the torrent on your server in it's default folder. Some client allow changing the download location on your server, in which case you can do this in the Transdroid torrent details screen with the disk icon in the bottom. (But this is not available/implemented for every torrent client type that Transdroid supports.)
