### ISSUE TITLE
[qbittorrent] Access denied (please check your settings)

### ISSUE THREAD

**Issue by layanto** [erickok/transdroid#534]
Using latest transdroid and latest qbittorrent, frequently getting access denied error. After clicking refresh, error disappeared. Seems to affect others too - see comments on https://github.com/erickok/transdroid/issues/516

**Comment by erickok** [comment]
Does it never conenct or only on retries? qBittorrent keeps changing its API and Auth and its starting to be very tough to support all versions, including older ones...

**Comment by layanto** [comment]
Alexandre Pinon commented below (I received email from GitHub but strangely I can't see his comment in GitHub):

I think it is because of the "version" API call being behind authentication.
See here:
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#general-information

    All API methods are under /api/v2/APIName/methodName, where APIName is a certain subgroup of API methods whose functionality is related.
    Either GET or POST can be used as the request type for all API methods.
    All API methods require authentication (except the /api/v2/auth/login method itself, obviously).
And in the Transdroid code, the version check is done unauthenticated.
Hence the Access Denied we have.

**Comment by layanto** [comment]
> Does it never conenct or only on retries? qBittorrent keeps changing its API and Auth and its starting to be very tough to support all versions, including older ones...

It does connect some times, other times it comes up with Access denied error.

**Comment by awsms** [comment]
Transdroid doesn't work with Qbittorrent >4.1

**Comment by dracula385** [comment]
same happens to me. It connects well via https to my qbitorrent and whilst it works i frequently see access denied.

**Comment by fexofenadine** [comment]
I currently get this issue only when using https but not http. Not sure if it helps diagnose it

**Comment by kevin-stuart** [comment]
I still think this problem is not yet solved. I tried qbittorrent 4.2.5.99~202004250119-7015-2c65b79~ubuntu18.04.1 with Transdroid 2.5.19.

I used nginx to proxy to qbittorrent to log the http status codes. It is strange, it logs a 404 when trying to login but immediately afterwards OKs are logged, but I do not see the results, instead Transdroid displays the red banner on the bottom and no list:

```
x.x.x.x - - [22/Jul/2020:15:07:08 +0200] "POST /api/v2/auth/login HTTP/1.1" 200 3 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:09 +0200] "POST /login HTTP/1.1" 404 0 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:09 +0200] "POST /api/v2/auth/login HTTP/1.1" 200 3 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:09 +0200] "POST /api/v2/app/version HTTP/1.1" 200 6 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:09 +0200] "POST /api/v2/sync/maindata?rid=0 HTTP/1.1" 200 2151 "-" "Transdroid Torrent Connect"
```

But if I now refresh, it works immediately OK with a slightly different turn of events, i.e. it calls torrents/info before sync:

```
x.x.x.x - - [22/Jul/2020:15:07:26 +0200] "POST /api/v2/auth/login HTTP/1.1" 200 3 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:26 +0200] "POST /api/v2/app/version HTTP/1.1" 200 6 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:26 +0200] "POST /api/v2/torrents/info HTTP/1.1" 200 1530 "-" "Transdroid Torrent Connect"
x.x.x.x - - [22/Jul/2020:15:07:26 +0200] "POST /api/v2/sync/maindata?rid=0 HTTP/1.1" 200 2151 "-" "Transdroid Torrent Connect"
```

Unfortunately, I have not found a precise way to reproduce. I just swipe to close Transdroid and hit refresh several times in Transdroid to provoke the error. As you can see, I just use Ubuntu 18.04, which can be spun up fairly easy for testing, with the most recent version of qBittorrent. The error can be provoked fairly easy if you kill the app often with 5-10 reloads it should appear at least once in my testing. I also switch to RSS and settings and back to expedite. Could you look into this and try to reproduce it?
