### ISSUE TITLE
Can´t connect to Synology Download Station if password includes special characters

### ISSUE THREAD

**Issue by jojjel** [erickok/transdroid#535]
If the Synology account password used includes a special character, ex !, # or &, I can´t connect, and error message is shown in Transdroid.
Remove the special character(s) in the accounts password and it´s possible to connect again, but the password is then weaker.
Running latest Synology DSM and latest Transdroid.

**Comment by fgerrits** [comment]
I have the same problem with a DS216play.

Any solution yet?

**Comment by erickok** [comment]
This particular part of code hasn't been touch since 2013 so I'm quite surprised it didn't arise earlier!

Unfortunately, I was also unable to reproduce. I just tried with a password that has an exclamation (`!`) mark in it and it connects just fine. That makes sense as it is 'just' basic auth and there's nothing really special about these characters. (No custom encoding or something and they are ascii anyway.)

Will close unless someone can recreate this scenario for me.
