### ISSUE TITLE
Notification diode and sound

### ISSUE THREAD

**Issue by florekem** [erickok/transdroid#548]
Are those functions working properly on android 9 (LineageOS 16)? For me diode is not working at all (lineage supports selecting color for my phone for sure), and sound is always phones default for notification, even if its set to different one in transdroid. Should I change some system settings to make it work?

**Comment by erickok** [comment]
It's because from Android 8 onwards the light (led) is only set on the Notification Channel (as can be seen in the OS-level notification settings for the app). I would have to add that. It can be done, but requires testing and my Pixel 3 doesn't have a led to test with so I hope I can still find some device with a led I can use...
