### ISSUE TITLE
Can't figure out how to get FTP downloads to work

### ISSUE THREAD

**Issue by dominickp** [erickok/transdroid#581]
Hi there, 

I spent last night trying to get FTP downloads working through the app and I'm not having any luck. But the problem is I am missing information I need to fix the issue. Is it possible to somehow see the FTP URL or some kind of FTP connection log that Transdrone is making? I can't see what is wrong.

I tried setting the Base FTP(S) url with a password in a bunch of different formats. I confirmed that the path is correct using another app "AndFTP" (AndFTP seems to be the only app which works with Transdrone by the way, apart from VLC which sometimes pops up as an option). But no matter what I do I seem to get:

> Download failed: {{filename}} not found

But I have no idea how to fix it. Can I see the URL that Transdrone is calculating so I can further debug? Is there another way to debug this issue? When using the "Base FTP(S) url" option I tried to verify using Chrome that my base URL is correct by making the entire path with the filename and entering the credentials and the file downloads there. I just have no idea how to debug the interaction between Transdrone and AndFTP.

Any pointers or maybe alternatives to AndFTP would be helpful. Thanks!

**Comment by erickok** [comment]
It's really bizarre how Android has so little FTP apps that allows integrating. Because without AndFTP (which is REALLY old now and not updated) Transdroid constructs a normal ftp:// url for any app willing to support it, yet I know of none. Actually, I made a little app called FTP Link Downloader for a bit but I didn't have time to properly support it. I guess I should rebuild it some time...

Anyway; what torrent client do you use? It depends on the client on how the url is constructed. Some require (or do not require, or even allow) setting a base url. Some do. Some supply too little information to properly construct the url in all cases (such as torrets with files in the root) while others do.

Not sure if I lof the file name; you can check the logs via the Help menu -> Send error report.

**Comment by dominickp** [comment]
>  Actually, I made a little app called FTP Link Downloader for a bit but I didn't have time to properly support it. I guess I should rebuild it some time...

Ah I saw that in a previous issue while I was debugging and was bummed to see the play store link didn't work. 

> Anyway; what torrent client do you use?

I'm using rTorrent

**Comment by dominickp** [comment]
I don't see anything related to the FTP download or the URLs it's producing in the error report log :(

**Comment by erickok** [comment]
I should make a little FTP client again...

It can work though with rTorrent, for sure. If you need help for your specific case, maybe send me an email at transdroid@2312.nl and supply som eextra details, such as how you usually connect to FTP (your address) and folder structure you use.
